class Unit
  def self.units
    units = [
        {
            :name => 'Riflemen',
            :desc => 'Riflemen are a cheap and well-rounded unit. They are decently fast and good for occupying trenches, serving as mobile reserves, and breaching enemy lines.',
            :rules => ['When riflemen attack enemy trenches, they can move into melee range to use their bayonet. Attacks with the bayonet deal damage to the trench AND any unit inside.', 'Can build a trench to greatly increase defensive strength.'],
            :strong => 'Mortars, Howitzers',
            :weak => 'Machine Guns, Field Guns',
            :img => '',
        },
        {
            :name => 'Machine Gun',
            :desc => 'Machine Guns can run and shoot like a riflemen, but can also stop to deploy their powerful machine gun. They automatically use their machine-gun when occupying a trench.',
            :rules => 'To use their main weapon, they must either setup, or get in a trench.',
            :strong => 'Infantry, Almost anything that comes too close',
            :weak => 'Trenches, Tanks, Field Guns',
            :img => '',
        },
        {
            :name => 'Mortar',
            :desc => 'Mortars have more range than riflemen or machine guns, but less overall damage. They do however get a large bonus vs Structures, Ships, and Tanks.',
            :rules => 'None',
            :strong => 'Trenches, Machine Guns, Ships, Tanks',
            :weak => 'Riflemen, Field Guns',
            :img => '',
        },
        {
            :name => 'Field Gun',
            :desc => 'Field Guns are light artillery. They fire a shrapnel shell deals splash damage to units in a wide area, dealing bonus damage to infantry.',
            :rules => ['Must setup to attack', 'Can only attack targets in front of it'],
            :strong => 'Infantry',
            :weak => 'Howitzers, Tanks',
            :img => '',
        },
        {
            :name => 'Howitzer',
            :desc => 'Howitzers are heavy artillery. They fire a high-explosive shell that deals bonus damage vs Artillery, Tanks, Structures, and Ships.',
            :rules => ['Must setup to attack', 'Can only attack targets in front of it'],
            :strong => 'Artillery, Tanks, Structures, and Ships',
            :weak => 'Infantry',
            :img => '',
        },
        {
            :name => 'Observation Balloon',
            :desc => 'Balloons can see farther than any other unit. Use them to see over terrain and spot distant units.',
            :rules => 'None',
            :strong => '',
            :weak => '',
            :img => '',
        },
        {
            :name => 'Airplane',
            :desc => 'Airplanes can see almost as far as balloons, but are much faster and can shoot other air units.',
            :rules => 'None',
            :strong => 'Balloons',
            :weak => '',
            :img => '',
        },
        {
            :name => 'Tank',
            :desc => 'Tanks are the only unit that can withstand machine-gun fire, making them useful as front-line troops. ',
            :rules => 'None',
            :strong => 'Machine Gun, Field Gun',
            :weak => 'Riflemen, Mortars, Howitzers',
            :img => '',
        },
        {
            :name => 'Railway Gun',
            :desc => 'Railway Guns heavy artillery. They are similar to howitzers, but have more range, and more damage vs Structures',
            :rules => ['Must setup to attack', 'Can only attack targets in front of it'],
            :strong => 'Artillery, Tanks, Structures, Ships',
            :weak => 'Infantry',
            :img => '',
        },
        {
            :name => 'Battleship',
            :desc => 'Battleships are very tough and have powerful attack that deals splash damage',
            :rules => 'None',
            :strong => 'Destroyer, Anything to close to the coast',
            :weak => 'Submarines, Mines, Fortress',
            :img => '',
        },
        {
            :name => 'Destroyer',
            :desc => 'Destroyers are fast warships that can scan their surroundings for submarines or mines.',
            :rules => 'None',
            :strong => 'Submarines, Mines',
            :weak => 'Battleships, Fortress, Mortars',
            :img => '',
        },
        {
            :name => 'Submarine',
            :desc => 'Submarines deal alot of damage, but are very fragile. They can submerge under water, making them invisible unless spotted by an enemy Destroyer or Port.',
            :rules => 'None',
            :strong => 'Battleships',
            :weak => 'Destroyers',
            :img => '',
        },
        {
            :name => 'Transport',
            :desc => 'Transports can load and unload units, allowing them to move across the water.',
            :rules => 'None',
            :strong => '',
            :weak => '',
            :img => '',
        },
        {
            :name => 'Mine',
            :desc => 'Mines detonate on enemy ships that come too close, killing them instantly.',
            :rules => 'Cannot move by themselves. Must be picked up and moved by Warships.',
            :strong => 'Ships',
            :weak => 'Destoyers scan ability, Ports',
            :img => '',
        },
        {
            :name => 'Worker',
            :desc => 'Workers build all your Structures. Most importantly, they can build the Barracks and Factory, which in turn can build all your units.',
            :rules => 'When unlike other infantry units, Workers dont automatically occupy their trench when they finish building. This allows them to queue up multiple trenches.',
            :strong => '',
            :weak => '',
            :img => '',
        },
    ]
    return units
  end
end